project snowflake_demo_olivier
table actors_dim      {
actor_geo_country_code varchar
actor_type_name varchar
actor_type_code varchar
actor_code varchar
actor_pk varchar [pk]
actor_name varchar
}
table events_fct      {
action_geo_longitude numeric
protest_fk varchar // [ref: - not_available.not_available]
action_geo_country_code varchar
action_geo_country_name varchar
event_pk varchar [pk]
action_geo_latitude numeric
event_ts date
action_geo_full_name varchar
}
table narratives_fct      {
narrative_pk varchar [pk]
event_fk varchar // [ref: - not_available.not_available]
actor_fk varchar // [ref: - not_available.not_available]
narrative varchar
}
table observations_fct      {
observation_pk varchar [pk]
published_date date
event_fk varchar // [ref: - not_available.not_available]
observation_keywords varchar
observation_page_description varchar
observer_fk varchar // [ref: - not_available.not_available]
observation_page_title varchar
observation_type varchar
observation_url varchar
}
table observers_dim      {
observer_domain varchar
observer_pk varchar [pk]
}
table protests_dim      {
protest_pk varchar [pk]
page_description_regex varchar
published_date_start date
protest_name varchar
published_date_end date
countries varchar
}
