project snowflake_demo_olivier
table actors_dim      {
actor_type_code varchar
actor_name varchar
actor_code varchar
actor_pk varchar [pk]
actor_type_name varchar
actor_geo_country_code varchar
}
table events_fct      {
action_geo_full_name varchar
action_geo_latitude numeric
action_geo_country_name varchar
protest_fk varchar // [ref: - not_available.not_available]
action_geo_country_code varchar
event_ts date
action_geo_longitude numeric
event_pk varchar [pk]
}
table narratives_fct      {
narrative_pk varchar [pk]
actor_fk varchar // [ref: - not_available.not_available]
event_fk varchar // [ref: - not_available.not_available]
narrative varchar
}
table observations_fct      {
observation_page_description varchar
published_date date
observation_page_title varchar
observation_type varchar
observer_fk varchar // [ref: - not_available.not_available]
observation_pk varchar [pk]
observation_url varchar
observation_keywords varchar
event_fk varchar // [ref: - not_available.not_available]
}
table observers_dim      {
observer_domain varchar
observer_pk varchar [pk]
}
table protests_dim      {
protest_pk varchar [pk]
protest_name varchar
published_date_start date
page_description_regex varchar
published_date_end date
countries varchar
}
