project snowflake_demo_olivier
{ database_type: 'bigquery' }
table actors_dim      {
actor_type_code text
actor_name text
actor_code text
actor_pk text [pk]
actor_type_name text
actor_geo_country_code text
}
table events_fct      {
action_geo_full_name text
action_geo_latitude number
action_geo_country_name text
protest_fk text // [ref: - not_available.not_available]
action_geo_country_code text
event_ts date
action_geo_longitude number
event_pk text [pk]
}
table narratives_fct      {
narrative_pk text [pk]
actor_fk text // [ref: - not_available.not_available]
event_fk text // [ref: - not_available.not_available]
narrative text
}
table observations_fct      {
observation_page_description text
published_date date
observation_page_title text
observation_type text
observer_fk text // [ref: - not_available.not_available]
observation_pk text [pk]
observation_url text
observation_keywords text
event_fk text // [ref: - not_available.not_available]
}
table observers_dim      {
observer_domain text
observer_pk text [pk]
}
table protests_dim      {
protest_pk text [pk]
protest_name text
published_date_start date
page_description_regex text
published_date_end date
countries text
}
