project project_value
{ database_type: 'bigquery' }
table wh_platform__bordereaux_fact      {
bordereaux_brokerage number
bordereaux_net number
bordereaux_created_at_ts timestamp_tz
bordereaux_tax number
bordereaux_tax_discount number
policy_fk text // [ref: - not_available.not_available]
bordereaux_gross_discount number
business_type_fk text // [ref: - not_available.not_available]
bordereaux_pk text [pk]
schedule_fk text // [ref: - not_available.not_available]
bordereaux_natural_key text
bordereaux_fee number
}
table wh_platform__brokers_fact      {
broker_name text
broker_pk text [pk]
broker_remuneration_start_ts timestamp_tz
broker_email_addresses variant
broker_created_at_ts timestamp_tz
broker_remuneration_rate number
}
table wh_platform__invoices_fact      {
invoice_pk text [pk]
invoice_payment_confirmed_at_ts timestamp_tz
invoice_tax number
invoice_gross_premium number
invoice_opened_at_ts timestamp_tz
invoice_status text
invoice_local_currency text
invoice_natural_key text
payment_fk text // [ref: - not_available.not_available]
currency_fk text // [ref: - not_available.not_available]
invoice_closed_at_ts timestamp_tz
invoice_due_at_ts timestamp_ntz
invoice_fees number
timezone_fk text // [ref: - not_available.not_available]
invoice_source_type text
policy_fk text // [ref: - not_available.not_available]
}
table wh_platform__policies_fact      {
policy_holder text
underwriter_fk text // [ref: - not_available.not_available]
policy_pk text [pk]
deposit_fk text // [ref: - not_available.not_available]
product_fk text // [ref: - not_available.not_available]
policy_inception_ts timestamp_ntz
policy_bound_at_ts timestamp_tz
policy_operation text
claim_fk text // [ref: - not_available.not_available]
policy_vertical text
policy_business_type text
policy_natural_key text
policy_status text
timezone_fk text // [ref: - not_available.not_available]
currency_fk text // [ref: - not_available.not_available]
customer_fk text // [ref: - not_available.not_available]
policy_end_at_ts timestamp_ntz
policy_installment_base boolean
introducer_fk text // [ref: - not_available.not_available]
}
table wh_platform__products_dim      {
product_type text
product_display_name text
product_pk text [pk]
product_name text
}
table wh_platform__quotes_fact      {
quote_operation text
underwriter_fk text // [ref: - not_available.not_available]
customer_fk text // [ref: - not_available.not_available]
product_fk text // [ref: - not_available.not_available]
quote_brokerage_premium number
quote_fee number
quote_tax number
discount_fk text // [ref: - not_available.not_available]
introducer_fk text // [ref: - not_available.not_available]
business_type_fk text // [ref: - not_available.not_available]
quote_excess number
quote_net_premium number
quote_pk text [pk]
quote_status text
quote_created_at_ts timestamp_tz
timezone_fk text // [ref: - not_available.not_available]
currency_fk text // [ref: - not_available.not_available]
}
table wh_platform__schedules_fact      {
schedule_end_at_ts timestamp_ntz
schedule_pk text [pk]
quote_fk text // [ref: - not_available.not_available]
batch_fk text // [ref: - not_available.not_available]
schedule_natural_key text
policy_fk text // [ref: - not_available.not_available]
schedule_bound_at_ts timestamp_tz
business_type_fk text // [ref: - not_available.not_available]
schedule_inception_ts timestamp_ntz
}
table wh_platform__vehicles_dim      {
vehicle_pk text [pk]
vehicle_gross_weight_kg number
vehicle_type text
vehicle_model text
vehicle_manufacturer text
}
table wh_platform_brokers_fact      {
broker_created_at_ts timestamp_tz
broker_remuneration_start_ts timestamp_tz
broker_remuneration_rate number
broker_email_addresses variant
broker_pk text [pk]
broker_name text
}
table wh_platform_products_dim      {
product_display_name text
product_pk text [pk]
product_name text
product_type text
}
table wh_platform_vehicles_dim      {
vehicle_gross_weight_kg number
vehicle_model text
vehicle_manufacturer text
vehicle_type text
vehicle_pk text [pk]
}
