project kaplan_poc
{ database_type: 'big_query' }
table int__study_plan      {
application_natural_key numeric
institution_natural_key numeric
intake_season varchar
intake_date date
}
table int_application_agents      {
agent_natural_key numeric
application_natural_key numeric
application_partner_natural_key numeric
is_main_agent boolean
}
table int_application_history      {
program_natural_key numeric
program_intake_natural_key numeric
institution_natural_key numeric
application_natural_key numeric
reporting_status varchar
reporting_status_group varchar
intake_name varchar
change varchar
program_name varchar
has_deferred varchar
program_code varchar
applications numeric
lost numeric
offers numeric
deposits numeric
enrolled numeric
change_count numeric
study_plan_version_number numeric
intake_date date
valid_to timestamp
valid_from timestamp
}
table int_application_quota      {
institution_natural_key numeric
student_natural_key varchar
program_natural_key numeric
program_intake_natural_key numeric
sponsor_natural_key numeric
agent_natural_key numeric
quota_item_natural_key numeric
application_natural_key numeric
quota_group varchar
exclude_nationality varchar
include_sponsor varchar
exclude_sponsor varchar
include_agent_region varchar
exclude_agent_region varchar
program varchar
institution_code varchar
application_status_group varchar
allow_program varchar
student_nationality varchar
study_plan_program_code varchar
degree_name varchar
university_code varchar
university_name varchar
college_code varchar
include_nationality varchar
allow_nationaility varchar
sales_region_name varchar
agent_name varchar
sponsor_name varchar
allow_sponsor varchar
allow_agent_region varchar
quota_year numeric
created_ts timestamp
}
table int_applications      {
institution_natural_key numeric
salesforce_opportunity_natural_key varchar
cas_team_owner_natural_key varchar
application_owner_natural_key varchar
sales_manager_natural_key varchar
student_natural_key varchar
application_natural_key numeric
sponsor_natural_key numeric
class_application_natural_key numeric
application_status_group varchar
application_status varchar
immigration_category varchar
payment_status varchar
returning_student varchar
accommodation_required varchar
intake_season varchar
sponsor_reference varchar
has_deferred varchar
learning_mode varchar
is_offer_letter_issued boolean
is_acceptance_form_issued boolean
is_visa_needed boolean
is_application_submitted boolean
is_application_completed boolean
is_confirmation_required boolean
has_second_agent boolean
intake_date date
created_ts timestamp
modified_ts timestamp
application_status_ts timestamp
}
table int_applications_history      {
salesforce_opportunity_natural_key varchar
cas_team_owner_natural_key varchar
application_natural_key numeric
student_natural_key varchar
sales_manager_natural_key varchar
application_owner_natural_key varchar
sponsor_natural_key numeric
class_application_natural_key numeric
old_title varchar
sponsor_reference varchar
new_title varchar
accommodation_required varchar
learning_mode varchar
returning_student varchar
application_status varchar
application_status_group varchar
payment_status varchar
immigration_category varchar
application_index numeric
is_offer_letter_issued boolean
is_current_application_record boolean
has_second_agent boolean
is_confirmation_required boolean
is_application_completed boolean
is_application_submitted boolean
is_visa_needed boolean
is_acceptance_form_issued boolean
application_status_log_created_ts timestamp
modified_ts timestamp
created_ts timestamp
application_valid_from timestamp
application_valid_to timestamp
}
table int_applications_history_i      {
class_application_natural_key numeric
application_natural_key numeric
student_natural_key varchar
sponsor_natural_key numeric
salesforce_opportunity_natural_key varchar
cas_team_owner_natural_key varchar
application_owner_natural_key varchar
sales_manager_natural_key varchar
application_status_group varchar
application_status varchar
new_title varchar
old_title varchar
sponsor_reference varchar
accommodation_required varchar
returning_student varchar
learning_mode varchar
immigration_category varchar
payment_status varchar
application_index numeric
is_acceptance_form_issued boolean
is_offer_letter_issued boolean
is_visa_needed boolean
is_application_submitted boolean
is_application_completed boolean
is_confirmation_required boolean
is_current_application_record boolean
has_second_agent boolean
application_valid_to timestamp
application_valid_from timestamp
created_ts timestamp
modified_ts timestamp
application_status_log_created_ts timestamp
}
table int_applications_status_history      {
application_status_log_natural_key numeric
application_natural_key numeric
sales_manager_natural_key varchar
student_natural_key varchar
immigration_category_natural_key numeric
learning_mode_natural_key numeric
accommodation_required_natural_key numeric
returning_student_natural_key numeric
payment_status_natural_key numeric
application_owner_natural_key varchar
cas_team_owner_natural_key varchar
salesforce_opportunity_natural_key varchar
application_status_reason_natural_key numeric
application_status_natural_key numeric
old_title varchar
new_title varchar
application_index numeric
is_current_application_record boolean
is_offer_letter_issued boolean
is_acceptance_form_issued boolean
is_application_submitted boolean
is_application_completed boolean
is_confirmation_required boolean
has_second_agent boolean
is_visa_needed boolean
modified_ts timestamp
application_status_log_created_ts timestamp
created_ts timestamp
application_valid_from timestamp
application_valid_to timestamp
}
table int_change_history      {
application_natural_key numeric
reporting_status varchar
reporting_status_group varchar
valid_to timestamp
valid_from timestamp
}
table int_core_agents      {
country_natural_key numeric
agent_natural_key numeric
agent_group varchar
agent_sales_channel varchar
agent_status varchar
agent_name varchar
agent_salesforce_business_key varchar
uk_based_agent boolean
}
table int_core_countries      {
country_natural_key numeric
sales_region_group_name varchar
sales_region_name varchar
country_nationality varchar
salesforce_country_key varchar
country_iso_key varchar
country_name varchar
is_sanctioned boolean
}
table int_core_country_mapping      {
country_natural_key numeric
schols_region varchar
sales_region_group_name varchar
sales_region_name varchar
nationality_iso_key varchar
valid_from timestamp
valid_to timestamp
}
table int_core_institutions      {
country_natural_key numeric
institution_natural_key numeric
institution_group varchar
institution_name varchar
institution_code varchar
institution_type varchar
}
table int_core_program_intakes      {
program_natural_key numeric
program_intake_natural_key numeric
program_status varchar
intake_season varchar
academic_year varchar
intake_name varchar
intake_quota_exists numeric
program_fee numeric
intake_date date
program_enrolment_start date
program_enrolment_end date
program_teaching_start_date date
program_teaching_end_date date
}
table int_core_programs      {
institution_unit_natural_key numeric
institution_natural_key numeric
program_natural_key numeric
instituiton_unit_department varchar
instituiton_unit_school varchar
instituiton_unit_faculty varchar
program_subject varchar
award_name varchar
award_code varchar
program_entry_type_code varchar
program_code varchar
program_name varchar
instituiton_unit_college varchar
entry_level varchar
program_type varchar
program_status varchar
program_level varchar
instituiton_unit_institute varchar
instituiton_unit_division varchar
award_type varchar
duration varchar
}
table int_core_scholarship_reason_owners      {
scholarship_reason_owner_natural_key numeric
budget_owner varchar
budget_pot varchar
sales_region_group varchar
}
table int_core_scholarship_reasons      {
scholarship_reason_natural_key numeric
scholarship_reason varchar
budget_pot varchar
}
table int_core_scholarships      {
application_natural_key numeric
study_plan_natural_key numeric
student_ledger_currency_code varchar
college_booking_item_name varchar
student_ledger_sop_line_item_actual_amount numeric
}
table int_core_sponsors      {
sponsor_natural_key numeric
country_natural_key numeric
sponsor_group varchar
sponsor_status varchar
sponsor_salesforce_business_key varchar
sponsor_name varchar
uk_sponsor boolean
}
table int_core_subjects      {
program_natural_key numeric
subject_natural_key numeric
program_subject varchar
program_subject_group varchar
}
table int_core_user_mapping      {
user_natural_key varchar
sales_region_group_name varchar
sales_region_name varchar
valid_from timestamp
valid_to timestamp
}
table int_core_users      {
user_natural_key varchar
user_fullname varchar
user_sales_region varchar
user_sales_region_group varchar
}
table int_institution_targets      {
institution_natural_key numeric
target_intake_name varchar
target_institution_name varchar
target_amt numeric
}
table int_new_programs      {
program_natural_key numeric
new_program_natural_key numeric
program_intake_natural_key numeric
institution_natural_key numeric
intake_name varchar
launch_name varchar
program_code varchar
program_name varchar
program_type varchar
award_name varchar
institution_code varchar
institution_name varchar
launch_date date
launch_expiry_date date
}
table int_pathways      {
study_plan_version_natural_key numeric
application_natural_key numeric
study_plan_program_natural_key numeric
study_plan_natural_key numeric
institution_natural_key numeric
study_plan_program_intake_natural_key numeric
study_plan_track_natural_key numeric
study_plan_intake_season varchar
study_plan_intake_name varchar
study_plan_intake_academic_year varchar
is_primary_progression varchar
study_plan_track_entry_type_code varchar
pathway_sk varchar
study_plan_program_name varchar
study_plan_program_entry_level varchar
study_plan_program_code varchar
track_type numeric
study_plan_version_number numeric
has_deferred boolean
is_current_version boolean
is_deferred boolean
study_plan_teaching_start_date date
study_plan_program_end_date date
study_plan_intake_date date
study_plan_program_start_date date
study_plan_teaching_end_date date
version_date date
study_plan_enrolment_date date
study_plan_modified_at timestamp
study_plan_created_at timestamp
version_created_at timestamp
version_modified_at_ts timestamp
}
table int_pathways__history      {
application_natural_key numeric
study_plan_natural_key numeric
study_plan_version_number numeric
version_date date
version_created_at_ts timestamp
valid_to timestamp
valid_from timestamp
version_modified_at_ts timestamp
}
table int_pathways_history      {
study_plan_track_natural_key numeric
study_plan_program_intake_natural_key numeric
study_plan_program_natural_key numeric
institution_natural_key numeric
study_plan_natural_key numeric
application_natural_key numeric
study_plan_track_entry_type_code varchar
pathway_sk varchar
study_plan_program_name varchar
study_plan_program_code varchar
study_plan_intake_season varchar
study_plan_program_entry_level varchar
study_plan_intake_name varchar
is_primary_progression varchar
has_deferred varchar
study_plan_intake_academic_year varchar
track_type numeric
study_plan_version_number numeric
study_plan_enrolment_date date
study_plan_program_start_date date
study_plan_program_end_date date
study_plan_teaching_start_date date
study_plan_teaching_end_date date
study_plan_intake_date date
version_date date
version_created_at_ts timestamp
study_plan_created_at timestamp
study_plan_modified_at timestamp
version_modified_at_ts timestamp
}
table int_pathways_i      {
study_plan_program_natural_key numeric
institution_natural_key numeric
study_plan_natural_key numeric
application_natural_key numeric
study_plan_track_natural_key numeric
program_intake_natural_key numeric
study_plan_program_intake_natural_key numeric
pathway_sk varchar
is_primary_progression varchar
study_plan_track_entry_type_code varchar
study_plan_intake_season varchar
study_plan_program_entry_level varchar
study_plan_program_code varchar
study_plan_program_name varchar
study_plan_version_number numeric
study_plan_program_start_date date
study_plan_program_end_date date
study_plan_teaching_start_date date
study_plan_enrolment_date date
study_plan_intake_date date
study_plan_teaching_end_date date
study_plan_created_at timestamp
study_plan_modified_at timestamp
}
table int_priority_programs      {
institution_natural_key numeric
program_intake_natural_key numeric
program_natural_key numeric
priority_program_natural_key numeric
course_type varchar
subject_group varchar
subject varchar
award_code varchar
priority_reason varchar
program_code varchar
program_name varchar
institution_code varchar
institution_name varchar
intake_name varchar
priority_row numeric
priority_end_date date
priority_start_date date
}
table int_progression_plan      {
program_intake_natural_key numeric
program_natural_key numeric
study_plan_version_natural_key numeric
study_plan_track_natural_key numeric
study_plan_track_entry_type_code varchar
}
table int_progression_plans      {
progression_plan_natural_key numeric
application_natural_key numeric
institution_natural_key numeric
progression_plan_track_natural_key numeric
progression_plan_program_natural_key numeric
progression_plan_program_intake_natural_key numeric
progression_plan_track_entry_type_code varchar
progression_plan_program_code varchar
progression_plan_program_name varchar
is_primary_progression varchar
progression_plan_entry_level varchar
pathway_sk varchar
progression_plan_intake_season varchar
progression_plan_version_number numeric
progression_plan_teaching_start_date date
progression_plan_intake_date date
progression_plan_enrolment_date date
progression_plan_teaching_end_date date
progression_plan_program_end_date date
progression_plan_program_start_date date
progression_plan_created_at timestamp
progression_plan_modified_at timestamp
}
table int_progression_plans_history      {
institution_natural_key numeric
progression_plan_program_natural_key numeric
progression_plan_natural_key numeric
application_natural_key numeric
progression_plan_track_natural_key numeric
progression_plan_program_intake_natural_key numeric
progression_plan_track_entry_type_code varchar
pathway_sk varchar
progression_plan_intake_season varchar
progression_plan_entry_level varchar
is_primary_progression varchar
progression_plan_program_code varchar
progression_plan_program_name varchar
progression_plan_version_number numeric
progression_plan_index numeric
is_current_progression_plan_record boolean
progression_plan_teaching_start_date date
progression_plan_program_end_date date
progression_plan_program_start_date date
progression_plan_teaching_end_date date
progression_plan_enrolment_date date
progression_plan_intake_date date
version_date date
version_created_at_ts timestamp
version_modified_at_ts timestamp
progression_plan_valid_to timestamp
progression_plan_valid_from timestamp
progression_plan_created_at timestamp
progression_plan_modified_at timestamp
}
table int_progression_study      {
application_natural_key numeric
institution_natural_key numeric
intake_season varchar
intake_date date
}
table int_quota_allocations      {
program_criteria varchar
university_code varchar
university_name varchar
college_code varchar
degree_concat varchar
quota_group varchar
nationaility_criteria varchar
sponsor_criteria varchar
agent_region_criteria varchar
progression_amt numeric
deposits_amt numeric
quota_year numeric
cas_enrolment_amt numeric
}
table int_quota_items      {
program_intake_natural_key numeric
program_natural_key numeric
institution_natural_key numeric
quota_item_natural_key numeric
degree_name varchar
quota_group varchar
program varchar
exclude_agent_region varchar
include_agent_region varchar
exclude_sponsor varchar
include_sponsor varchar
exclude_nationality varchar
include_nationality varchar
college_code varchar
university_name varchar
university_code varchar
quota_year numeric
}
table int_sales_budgets      {
institution_natural_key numeric
budget_group varchar
institution_name varchar
sales_region_group varchar
budget_name varchar
intake_name varchar
entry_type_code varchar
row numeric
sales_budgets numeric
}
table int_sales_region_targets      {
country_natural_key numeric
target_sales_channel varchar
target_intake_name varchar
target_country_name varchar
target_sales_region varchar
target_sales_region_group varchar
target_amt numeric
}
table int_scholarship_budgets      {
intake_name varchar
sales_region_group varchar
schols_region varchar
budget_pot varchar
budget_owner varchar
budget_amt numeric
}
table int_scholarship_targets      {
schols_region varchar
sales_region_group varchar
intake_name varchar
schols_target numeric
schols_budget numeric
}
table int_scholarships      {
application_natural_key numeric
study_plan_natural_key numeric
student_ledger_sop_line_item_natural_key numeric
budget_pot varchar
application_status_group varchar
student_ledger_currency_code varchar
scholarship_reason varchar
scholarship_note varchar
student_ledger_sop_line_item_actual_amount numeric
created_at timestamp
}
table int_students      {
student_class_natural_key varchar
student_salesforce_natural_key varchar
country_natural_key numeric
student_kss_natural_key varchar
student_natural_key varchar
country_iso_key varchar
student_source varchar
student_nationality varchar
nationality_iso_key varchar
student_fullname varchar
student_gender varchar
student_dob date
student_modified_at timestamp
student_created_at timestamp
}
table int_study_plan      {
program_intake_natural_key numeric
program_natural_key numeric
study_plan_version_natural_key numeric
study_plan_track_natural_key numeric
study_plan_track_entry_type_code varchar
}
table int_study_plan_history      {
program_natural_key numeric
institution_natural_key numeric
program_intake_natural_key numeric
study_plan_natural_key numeric
application_natural_key numeric
academic_year varchar
intake_name varchar
program_code varchar
program_name varchar
study_plan_version_number numeric
intake_date date
valid_to timestamp
valid_from timestamp
}
table int_study_plans      {
study_plan_natural_key numeric
application_natural_key numeric
institution_natural_key numeric
study_plan_version_natural_key numeric
study_plan_program_natural_key numeric
study_plan_track_natural_key numeric
study_plan_program_intake_natural_key numeric
pathway_sk varchar
study_plan_program_code varchar
study_plan_track_entry_type_code varchar
is_primary_progression varchar
study_plan_program_name varchar
study_plan_intake_academic_year varchar
study_plan_intake_season varchar
study_plan_program_entry_level varchar
study_plan_intake_name varchar
track_type numeric
study_plan_version_number numeric
is_deferred boolean
has_deferred boolean
is_current_version boolean
study_plan_enrolment_date date
version_date date
study_plan_program_start_date date
study_plan_program_end_date date
study_plan_teaching_start_date date
study_plan_teaching_end_date date
study_plan_intake_date date
study_plan_created_at timestamp
study_plan_modified_at timestamp
version_created_at timestamp
version_modified_at_ts timestamp
}
table int_study_plans_history      {
study_plan_program_intake_natural_key numeric
application_natural_key numeric
study_plan_natural_key numeric
institution_natural_key numeric
study_plan_program_natural_key numeric
study_plan_track_natural_key numeric
study_plan_intake_academic_year varchar
study_plan_intake_name varchar
study_plan_intake_season varchar
has_deferred varchar
is_primary_progression varchar
study_plan_track_entry_type_code varchar
study_plan_program_entry_level varchar
study_plan_program_name varchar
pathway_sk varchar
study_plan_program_code varchar
study_plan_index numeric
track_type numeric
study_plan_version_number numeric
is_current_study_plan_record boolean
study_plan_enrolment_date date
version_date date
study_plan_intake_date date
study_plan_teaching_end_date date
study_plan_program_start_date date
study_plan_program_end_date date
study_plan_teaching_start_date date
version_modified_at_ts timestamp
version_created_at_ts timestamp
study_plan_valid_to timestamp
study_plan_valid_from timestamp
study_plan_modified_at timestamp
study_plan_created_at timestamp
}
