project kaplan_poc
table stg_kss_application_partners      {
application_partner_natural_key numeric
application_natural_key numeric
business_natural_key numeric
counsellor_natural_key numeric
liaison_natural_key numeric
is_main_agent boolean
partner_type varchar
application_partner_reference varchar
}
table stg_kss_application_status_logs      {
application_status_log_natural_key numeric
application_natural_key numeric
old_status_natural_key numeric
new_status_natural_key numeric
reason_natural_key numeric
status_reference varchar
application_status_log_created_ts timestamp
application_status_log_modified_ts timestamp
}
table stg_kss_applications      {
application_natural_key numeric
student_natural_key varchar
sales_manager_natural_key varchar
application_owner_natural_key varchar
cas_team_owner_natural_key varchar
salesforce_opportunity_natural_key varchar
application_status_natural_key numeric
application_status_reason_natural_key numeric
payment_status_natural_key numeric
immigration_category_natural_key numeric
learning_mode_natural_key numeric
returning_student_natural_key numeric
accommodation_required_natural_key numeric
is_offer_letter_issued boolean
is_acceptance_form_issued boolean
is_visa_needed boolean
is_application_submitted boolean
is_application_completed boolean
is_confirmation_required boolean
has_second_agent boolean
created_ts timestamp
modified_ts timestamp
}
table stg_kss_awards      {
award_natural_key numeric
award_type_natural_key numeric
award_code varchar
award_name varchar
}
table stg_kss_businesses      {
business_natural_key numeric
status_natural_key numeric
salesforce_business_key varchar
country_iso_key varchar
business_name varchar
business_group varchar
business_type varchar
}
table stg_kss_catalogue_pick_list_items      {
pick_list_natural_key numeric
pick_list_type varchar
description varchar
}
table stg_kss_college_booking_item      {
college_booking_item_natural_key numeric
scholarship_reason varchar
}
table stg_kss_configurations      {
configuration_natural_key numeric
config_value varchar
}
table stg_kss_countries      {
country_natural_key numeric
country_iso_key varchar
country_name varchar
nationality_iso_key varchar
salesforce_country_key varchar
sales_region_name varchar
is_sanctioned boolean
}
table stg_kss_institution_unit      {
institution_unit_name_natural_key numeric
institution_natural_key numeric
institution_unit_name varchar
}
table stg_kss_institution_unit_details      {
institution_unit_detail_natural_key numeric
institution_unit_natural_key numeric
institution_unit_type_natural_key numeric
institution_unit_name varchar
}
table stg_kss_institutions      {
institution_natural_key numeric
country_iso_key varchar
institution_code varchar
institution_name varchar
institution_short_name varchar
institution_type varchar
}
table stg_kss_modules      {
module_natural_key numeric
module_code varchar
module_name varchar
}
table stg_kss_nationalities      {
nationality_natural_key numeric
nationality varchar
nationality_key varchar
nationality_iso_key varchar
}
table stg_kss_program_activity_types      {
program_activity_type_natural_key numeric
program_activity_type_description varchar
}
table stg_kss_program_dates      {
program_date_natural_key numeric
program_intake_natural_key numeric
activity_type numeric
start_date date
end_date date
}
table stg_kss_program_intake      {
program_intake_natural_key numeric
program_natural_key numeric
season_natural_key numeric
program_status_natural_key numeric
program_fee numeric
currency_code varchar
intake_date date
intake_quota_exists numeric
}
table stg_kss_program_subject_area      {
program_subject_area_natural_key numeric
program_natural_key numeric
subject_natural_key numeric
}
table stg_kss_program_subjects      {
subject_natural_key varchar
program_subject varchar
}
table stg_kss_programs      {
program_natural_key numeric
institution_natural_key numeric
program_award_natural_key numeric
institution_unit_natural_key numeric
program_level_natural_key numeric
program_entry_level_natural_key numeric
program_type_natural_key numeric
program_status_natural_key numeric
program_duration_natural_key numeric
program_name varchar
program_code varchar
program_duration_length varchar
program_entry_type_code varchar
subject_natural_key varchar
}
table stg_kss_status      {
status_natural_key numeric
parent_status_natural_key numeric
reference varchar
reporting_status varchar
reporting_status_group varchar
title varchar
}
table stg_kss_student_ledger_sop_header      {
student_ledger_sop_header_natural_key numeric
student_ledger_currency_code varchar
}
table stg_kss_student_ledger_sop_line_item      {
student_ledger_sop_line_item_natural_key numeric
student_ledger_sop_line_item_status varchar
student_ledger_sop_line_item_actual_amount numeric
}
table stg_kss_students      {
student_natural_key varchar
student_kss_natural_key varchar
student_class_natural_key varchar
student_salesforce_natural_key varchar
student_fullname varchar
student_gender varchar
country_iso_key varchar
student_source varchar
nationality_key varchar
student_dob date
student_created_at timestamp
student_modified_at timestamp
}
table stg_kss_study_plan      {
study_plan_natural_key numeric
application_natural_key numeric
enrolment_natural_key varchar
study_plan_version_number numeric
study_plan_created_at timestamp
study_plan_modified_at timestamp
}
table stg_kss_study_plan_booking_item      {
study_plan_booking_item_natural_key numeric
study_plan_natural_key numeric
student_ledger_sop_line_item_natural_key numeric
student_ledger_sop_header_natural_key numeric
study_plan_booking_item numeric
study_plan_booking_item_is_active varchar
scholarship_note varchar
study_plan_booking_item_category_code varchar
created_at timestamp
}
table stg_kss_study_plan_pick_list_items      {
pick_list_natural_key numeric
study_plan_pick_list_type varchar
study_plan_pick_list_description varchar
}
table stg_kss_study_plan_program_dates      {
study_plan_program_date_natural_key numeric
study_plan_track_natural_key numeric
program_activity_type_natural_key numeric
program_intake_natural_key numeric
study_plan_program_start_date date
study_plan_program_end_date date
}
table stg_kss_study_plan_program_intake      {
study_plan_program_intake_natural_key numeric
study_plan_track_natural_key numeric
program_intake_natural_key numeric
intake_date date
intake_season varchar
academic_year varchar
intake_name varchar
}
table stg_kss_study_plan_programs      {
study_plan_program_natural_key numeric
study_plan_track_natural_key numeric
program_natural_key numeric
institution_natural_key numeric
program_entry_level varchar
program_code varchar
program_name varchar
}
table stg_kss_study_plan_term      {
study_plan_term_natural_key numeric
program_intake_natural_key numeric
study_plan_teaching_end_date date
study_plan_teaching_start_date date
}
table stg_kss_study_plan_tracks      {
study_plan_track_natural_key numeric
study_plan_version_natural_key numeric
program_natural_key numeric
program_intake_natural_key numeric
track_type numeric
study_plan_track_entry_type_code varchar
is_primary_progression varchar
}
table stg_kss_study_plan_version      {
study_plan_version_natural_key numeric
study_plan_natural_key numeric
study_plan_version_number numeric
created_at_ts timestamp
modified_at_ts timestamp
version_date date
}
table stg_kss_study_plan_versions      {
study_plan_version_natural_key numeric
study_plan_natural_key numeric
study_plan_version_number numeric
created_ts timestamp
modified_ts timestamp
study_plan_enrolment_date date
version_date date
}
table stg_kss_study_plans      {
study_plan_natural_key numeric
application_natural_key numeric
enrolment_natural_key varchar
study_plan_version_number numeric
study_plan_created_at timestamp
study_plan_modified_at timestamp
}
table stg_kss_studyplan_program_intake      {
program_intake_natural_key numeric
intake_date date
intake_season varchar
}
table stg_kss_subject      {
subject_natural_key varchar
subject varchar
}
table stg_kss_subject_area      {
subject_natural_key numeric
subject varchar
}
table stg_kss_users      {
user_natural_key varchar
user_fullname varchar
}
table stg_map_countries      {
country_name varchar
sales_region_name varchar
sales_region_group_name varchar
schols_region varchar
valid_from timestamp
valid_to timestamp
}
table stg_map_institution_groups      {
institution_name varchar
institution_group varchar
}
table stg_map_institution_targets      {
target_intake_name varchar
target_institution_name varchar
target_amt numeric
}
table stg_map_institution_targets_2      {
target_intake_name varchar
target_institution_name varchar
target_amt numeric
}
table stg_map_new_programs      {
launch_name varchar
intake_name varchar
program_code varchar
program_name varchar
institution_code varchar
institution_name varchar
launch_date date
launch_expiry_date date
}
table stg_map_priority_programs      {
priority_reason varchar
program_code varchar
program_name varchar
award_code varchar
subject varchar
subject_group varchar
course_type varchar
institution_code varchar
institution_name varchar
intake_name varchar
priority_start_date date
priority_end_date date
}
table stg_map_quota_allocations      {
university_code varchar
university_name varchar
college_code varchar
degree_concat varchar
include_nationality varchar
exclude_nationality varchar
include_sponsor varchar
exclude_sponsor varchar
include_agent_region varchar
exclude_agent_region varchar
program varchar
quota_group varchar
notes varchar
comments varchar
quota_year numeric
deposits_amt numeric
cas_enrolment_amt numeric
progression_amt numeric
}
table stg_map_quota_items      {
university_code varchar
university_name varchar
college_code varchar
degree_name varchar
include_nationality varchar
exclude_nationality varchar
include_sponsor varchar
exclude_sponsor varchar
include_agent_region varchar
exclude_agent_region varchar
program varchar
quota_group varchar
quota_year numeric
}
table stg_map_sales_budgets      {
budget_group varchar
budget_name varchar
intake_name varchar
institution_name varchar
entry_type_code varchar
sales_region_group varchar
sales_budgets numeric
}
table stg_map_sales_region_targets      {
target_intake_name varchar
target_country_name varchar
target_sales_region varchar
target_sales_region_group varchar
target_sales_channel varchar
target_amt numeric
}
table stg_map_sales_region_targets_2      {
target_intake_name varchar
target_country_name varchar
target_sales_region varchar
target_sales_region_group varchar
target_sales_channel varchar
target_amt numeric
}
table stg_map_scholarship_budgets      {
intake_name varchar
sales_region_group varchar
schols_region varchar
schols_budget numeric
budget_pot_1 numeric
budget_pot_2 numeric
budget_pot_3 numeric
budget_pot_4 numeric
budget_pot_5 numeric
budget_pot_6 numeric
budget_pot_7 numeric
budget_pot_8 numeric
budget_pot_9 numeric
budget_pot_10 numeric
}
table stg_map_scholarship_budgets_pots      {
budget_pot_1 varchar
budget_pot_2 varchar
budget_pot_3 varchar
budget_pot_4 varchar
budget_pot_5 varchar
budget_pot_6 varchar
budget_pot_7 varchar
budget_pot_8 varchar
budget_pot_9 varchar
budget_pot_10 varchar
}
table stg_map_scholarship_reason_owners      {
sales_region_group varchar
budget_pot varchar
budget_owner varchar
}
table stg_map_scholarship_reasons      {
scholarship_reason varchar
budget_pot varchar
}
table stg_map_status_reasons      {
status_reason varchar
team varchar
}
table stg_map_subject_groups      {
subject varchar
subject_group varchar
}
table stg_map_uk_based_agents      {
agent_name varchar
}
table stg_map_uk_sponsors      {
sponsor_name varchar
}
table stg_map_user_sales_regions      {
user_fullname varchar
sales_region varchar
sales_region_group varchar
valid_from timestamp
valid_to timestamp
}
