project snowflake_demo_olivier
{ database_type: 'snowflake' }
table stg__gdelt__enhanced_mentions      {
page_name varchar
page_description varchar
file_name varchar
page_title varchar
keywords varchar
mention_url varchar
source_file_date date
}
table stg__gdelt__events      {
action_geo_country_code varchar
actor2_geo_country_code varchar
actor1_type2_code varchar
actor1_geo_full_name varchar
actor1_geo_feature_id varchar
actor2_name varchar
mention_url varchar
actor2_known_group_code varchar
actor2_geo_full_name varchar
action_geo_feature_id varchar
actor1_ethnic_code varchar
actor2_geo_adm2_code varchar
actor1_religion2_code varchar
actor1_geo_adm2_code varchar
actor1_country_code varchar
actor1_code varchar
actor1_type1_code varchar
actor1_religion1_code varchar
actor2_code varchar
actor2_type2_code varchar
actor1_known_group_code varchar
event_code varchar
actor2_geo_adm1_code varchar
action_geo_adm2_code varchar
source_url varchar
event_base_code varchar
actor2_type1_code varchar
actor1_name varchar
actor2_ethnic_code varchar
actor1_type3_code varchar
actor2_country_code varchar
actor1_geo_adm1_code varchar
actor2_religion1_code varchar
event_root_code varchar
action_geo_full_name varchar
actor1_geo_country_code varchar
actor2_type3_code varchar
actor2_geo_feature_id varchar
action_geo_adm1_code varchar
actor2_religion2_code varchar
avg_tone numeric
published_date_fraction_date numeric
published_date_my numeric
is_root_event numeric
action_geo_longitude numeric
actor2_geo_longitude numeric
actor2_geo_type numeric
actor1_geo_latitude numeric
num_articles numeric
num_mentions numeric
num_sources numeric
actor1_geo_type numeric
action_geo_type numeric
quad_class numeric
actor1_geo_longitude numeric
action_geo_latitude numeric
gdelt_event_natural_key numeric
published_date_year numeric
actor2_geo_latitude numeric
goldstein_scale numeric
published_date date
creation_ts timestamp
}
table stg__gdelt__ml_enriched_mentions      {
page_title varchar
page_description varchar
page_name varchar
file_name varchar
keywords varchar
mention_url varchar
is_relevant boolean
source_file_date date
}
