project snowflake_demo_olivier
{ database_type: 'snowflake' }
table actors_dim      {
actor_pk varchar [pk]
actor_geo_country_code varchar
actor_code varchar
actor_name varchar
actor_type_code varchar
actor_type_name varchar
}
table events_fct      {
event_pk varchar [pk]
protest_fk varchar [ref: - protests_dim.protest_pk]
action_geo_country_name varchar
action_geo_full_name varchar
action_geo_country_code varchar
action_geo_longitude numeric
action_geo_latitude numeric
event_ts date
}
table narratives_fct      {
narrative_pk varchar [pk]
actor_fk varchar [ref: - actors_dim.actor_pk]
event_fk varchar [ref: - events_fct.event_pk]
narrative varchar
}
table observations_fct      {
observation_pk varchar [pk]
event_fk varchar [ref: - events_fct.event_pk]
observer_fk varchar [ref: - observers_dim.observer_pk]
observation_page_description varchar
observation_keywords varchar
observation_url varchar
observation_type varchar
observation_page_title varchar
published_date date
}
table observers_dim      {
observer_pk varchar [pk]
observer_domain varchar
}
table protests_dim      {
protest_pk varchar [pk]
countries varchar
protest_name varchar
page_description_regex varchar
published_date_start date
published_date_end date
}
