cube (`wh_marketing__web_event_items_fact_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_event_items_fact`,
extends: wh_marketing__web_event_items_fact,
measures: {
count_of_web_event_item_pk:  {
  sql: `web_event_item_pk`,
  type: `count`,
} ,
sum_of_web_event_item_price_in_usd:  {
  sql: `web_event_item_price_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_item_price:  {
  sql: `web_event_item_price`,
  type: `sum`,
} ,
sum_of_web_event_item_quantity:  {
  sql: `web_event_item_quantity`,
  type: `sum`,
} ,
sum_of_web_event_item_revenue_in_usd:  {
  sql: `web_event_item_revenue_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_item_revenue:  {
  sql: `web_event_item_revenue`,
  type: `sum`,
} ,
sum_of_web_event_item_refund_in_usd:  {
  sql: `web_event_item_refund_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_item_refund:  {
  sql: `web_event_item_refund`,
  type: `sum`,
} ,
}});
cube (`wh_marketing__web_event_parameters_fact_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_event_parameters_fact`,
extends: wh_marketing__web_event_parameters_fact,
measures: {
count_of_web_event_parameter_pk:  {
  sql: `web_event_parameter_pk`,
  type: `count`,
} ,
sum_of_web_event_parameter_int_value:  {
  sql: `web_event_parameter_int_value`,
  type: `sum`,
} ,
sum_of_web_event_parameter_float_value:  {
  sql: `web_event_parameter_float_value`,
  type: `sum`,
} ,
sum_of_web_event_parameter_double_value:  {
  sql: `web_event_parameter_double_value`,
  type: `sum`,
} ,
}});
cube (`wh_marketing__web_event_query_parameters_fact_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_event_query_parameters_fact`,
extends: wh_marketing__web_event_query_parameters_fact,
measures: {
count_of_web_event_query_parameter_pk:  {
  sql: `web_event_query_parameter_pk`,
  type: `count`,
} ,
}});
cube (`wh_marketing__web_event_visitor_properties_fact_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_event_visitor_properties_fact`,
extends: wh_marketing__web_event_visitor_properties_fact,
measures: {
count_of_web_event_visitor_property_pk:  {
  sql: `web_event_visitor_property_pk`,
  type: `count`,
} ,
sum_of_web_event_visitor_property_int_value:  {
  sql: `web_event_visitor_property_int_value`,
  type: `sum`,
} ,
sum_of_web_event_visitor_property_float_value:  {
  sql: `web_event_visitor_property_float_value`,
  type: `sum`,
} ,
sum_of_web_event_visitor_property_double_value:  {
  sql: `web_event_visitor_property_double_value`,
  type: `sum`,
} ,
}});
cube (`wh_marketing__web_events_fact_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_events_fact`,
extends: wh_marketing__web_events_fact,
measures: {
count_of_web_event_pk:  {
  sql: `web_event_pk`,
  type: `count`,
} ,
sum_of_web_event_sequence_number:  {
  sql: `web_event_sequence_number`,
  type: `sum`,
} ,
sum_of_web_event_intent_rank:  {
  sql: `web_event_intent_rank`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_total_item_quantity:  {
  sql: `web_event_ecommerce_total_item_quantity`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_unique_items:  {
  sql: `web_event_ecommerce_unique_items`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_purchase_revenue_in_usd:  {
  sql: `web_event_ecommerce_purchase_revenue_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_purchase_revenue:  {
  sql: `web_event_ecommerce_purchase_revenue`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_refund_value_in_usd:  {
  sql: `web_event_ecommerce_refund_value_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_refund_value:  {
  sql: `web_event_ecommerce_refund_value`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_shipping_value_in_usd:  {
  sql: `web_event_ecommerce_shipping_value_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_shipping_value:  {
  sql: `web_event_ecommerce_shipping_value`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_tax_value_in_usd:  {
  sql: `web_event_ecommerce_tax_value_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_ecommerce_tax_value:  {
  sql: `web_event_ecommerce_tax_value`,
  type: `sum`,
} ,
sum_of_web_event_value_in_usd:  {
  sql: `web_event_value_in_usd`,
  type: `sum`,
} ,
sum_of_web_event_entrances:  {
  sql: `web_event_entrances`,
  type: `sum`,
} ,
sum_of_web_event_device_time_zone_offset_seconds:  {
  sql: `web_event_device_time_zone_offset_seconds`,
  type: `sum`,
} ,
sum_of_web_event_ga_engaged_event:  {
  sql: `web_event_ga_engaged_event`,
  type: `sum`,
} ,
sum_of_web_event_was_visitor_natural_key_null:  {
  sql: `web_event_was_visitor_natural_key_null`,
  type: `sum`,
} ,
sum_of_web_event_was_session_natural_key_null:  {
  sql: `web_event_was_session_natural_key_null`,
  type: `sum`,
} ,
}});
cube (`wh_marketing__web_sessions_xa_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_sessions_xa`,
extends: wh_marketing__web_sessions_xa,
measures: {
count_of_web_session_pk:  {
  sql: `web_session_pk`,
  type: `count`,
} ,
sum_of_web_session_wh_generated:  {
  sql: `web_session_wh_generated`,
  type: `sum`,
} ,
sum_of_web_session_number:  {
  sql: `web_session_number`,
  type: `sum`,
} ,
sum_of_web_session_ga_engaged_session:  {
  sql: `web_session_ga_engaged_session`,
  type: `sum`,
} ,
sum_of_web_session_total_events:  {
  sql: `web_session_total_events`,
  type: `sum`,
} ,
sum_of_web_session_total_ga_engaged_events:  {
  sql: `web_session_total_ga_engaged_events`,
  type: `sum`,
} ,
sum_of_web_session_total_page_views:  {
  sql: `web_session_total_page_views`,
  type: `sum`,
} ,
sum_of_web_session_total_search_results_page_views:  {
  sql: `web_session_total_search_results_page_views`,
  type: `sum`,
} ,
sum_of_web_session_total_vehicle_details_page_views:  {
  sql: `web_session_total_vehicle_details_page_views`,
  type: `sum`,
} ,
sum_of_web_session_total_level_2_events:  {
  sql: `web_session_total_level_2_events`,
  type: `sum`,
} ,
sum_of_web_session_total_level_3_events:  {
  sql: `web_session_total_level_3_events`,
  type: `sum`,
} ,
sum_of_web_session_total_level_4_events:  {
  sql: `web_session_total_level_4_events`,
  type: `sum`,
} ,
sum_of_web_session_total_level_2_vdp:  {
  sql: `web_session_total_level_2_vdp`,
  type: `sum`,
} ,
sum_of_web_session_total_intents:  {
  sql: `web_session_total_intents`,
  type: `sum`,
} ,
sum_of_web_session_first_not_null_device_time_zone_offset_seconds:  {
  sql: `web_session_first_not_null_device_time_zone_offset_seconds`,
  type: `sum`,
} ,
sum_of_web_session_duration_seconds:  {
  sql: `web_session_duration_seconds`,
  type: `sum`,
} ,
}});
cube (`wh_marketing__web_visitors_xa_extended`, {
sql: `select * from analytics_qa.wh_marketing__web_visitors_xa`,
extends: wh_marketing__web_visitors_xa,
measures: {
count_of_web_visitor_pk:  {
  sql: `web_visitor_pk`,
  type: `count`,
} ,
sum_of_web_visitor_wh_generated:  {
  sql: `web_visitor_wh_generated`,
  type: `sum`,
} ,
sum_of_web_visitor_total_sessions:  {
  sql: `web_visitor_total_sessions`,
  type: `sum`,
} ,
sum_of_web_visitor_total_events:  {
  sql: `web_visitor_total_events`,
  type: `sum`,
} ,
sum_of_web_visitor_ga_engaged_visitor:  {
  sql: `web_visitor_ga_engaged_visitor`,
  type: `sum`,
} ,
sum_of_web_visitor_total_page_views:  {
  sql: `web_visitor_total_page_views`,
  type: `sum`,
} ,
sum_of_web_visitor_total_search_results_page_views:  {
  sql: `web_visitor_total_search_results_page_views`,
  type: `sum`,
} ,
sum_of_web_visitor_total_vehicle_details_page_views:  {
  sql: `web_visitor_total_vehicle_details_page_views`,
  type: `sum`,
} ,
sum_of_web_visitor_total_level_2_events:  {
  sql: `web_visitor_total_level_2_events`,
  type: `sum`,
} ,
sum_of_web_visitor_total_level_3_events:  {
  sql: `web_visitor_total_level_3_events`,
  type: `sum`,
} ,
sum_of_web_visitor_total_level_4_events:  {
  sql: `web_visitor_total_level_4_events`,
  type: `sum`,
} ,
sum_of_web_visitor_total_level_2_vdp:  {
  sql: `web_visitor_total_level_2_vdp`,
  type: `sum`,
} ,
}});
